### ISSUE TITLE
Not working correctly with polymorphic associations

### ISSUE THREAD

**Issue by daekrist** [nerde/left_join#1]
Hello.
I've noticed that left_join isn't adding `AND imageable_type='Product'` in my case (I have polymorphic association in my application):

`SELECT  products.*, COUNT(DISTINCT images.id) as images_count FROM "products" LEFT OUTER JOIN "images" ON "products"."id" = "images"."imageable_id" GROUP BY products.id  ORDER BY "products"."created_at" DESC`

Could you, please, fix it? :)

**Comment by nerde** [comment]
Thanks for your bug report @daekrist, I will try to fix it as soon as I find time for it. I've been a bit busy lately. If you know of a simple solution, feel free to make a Pull Request :)

Cheers.

**Comment by nerde** [comment]
@daekrist good news. I fixed the problem and improved the code (a lot). Please, use version `0.2.0`.
